<a href="https://colab.research.google.com/github/MilagrosPozzo/Programacion-1/blob/main/3_7_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducción a las matrices en NumPy

Hasta ahora, hemos trabajado con lo que podríamos llamar "arreglos" en Python usando listas, una funcionalidad nativa del lenguaje. Pero hemos mencionado también que Python, en su forma estándar, no tiene un verdadero soporte para "arreglos" como lo conocemos en otros lenguajes de programación. Y sí, eso es cierto.

Pero aquí es donde NumPy entra en juego. NumPy es una biblioteca de Python que nos proporciona una estructura de datos tipo arreglo, el `ndarray`, optimizada para cálculos numéricos eficientes. En este módulo, vamos a aprender cómo trabajar con estos "arreglos" utilizando NumPy. Esta habilidad es esencial para muchas áreas en ciencia de datos, aprendizaje automático y computación científica, ya que nos permitirá manejar y realizar operaciones con conjuntos de datos numéricos de manera eficiente.

# Creación de matrices en NumPy

Podemos crear matrices en NumPy de varias formas. Aquí hay algunos ejemplos:

In [1]:
import numpy as np

# Crear una matriz a partir de una lista de listas
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("A =\n", A)

# Crear una matriz de ceros
B = np.zeros((3, 3))
print("\nB =\n", B)

# Crear una matriz de unos
C = np.ones((3, 3))
print("\nC =\n", C)

# Crear una matriz con valores aleatorios
D = np.random.rand(3, 3)
print("\nD =\n", D)

A =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

B =
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

C =
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

D =
 [[0.28551293 0.40943069 0.99360407]
 [0.65074772 0.62694518 0.9082299 ]
 [0.46113091 0.43278335 0.05179635]]


Seguramente habrás notado en algún desafío anterior el uso de as en líneas de código como import libreria as lib. as en Python se utiliza para crear un alias durante la importación de un módulo. En este caso, estamos importando el módulo numpy y asignándole el alias np. Esto se hace por conveniencia para hacer el código más legible y conciso.

Después de esto, puedes usar el prefijo np. en lugar de numpy. para llamar a las funciones y métodos del módulo numpy. Esto es especialmente útil para módulos con nombres largos o que se utilizan con frecuencia.

El alias np para numpy es una convención ampliamente adoptada por la comunidad de Python, especialmente entre los científicos de datos, ingenieros y desarrolladores que utilizan numpy para el cálculo numérico. Utilizar estas convenciones ayuda a mantener el código coherente y fácil de leer entre diferentes proyectos y equipos. Sin embargo, podrías elegir cualquier nombre que desees para el alias. Por ejemplo, import numpy as nump también sería válido, pero no es comúnmente utilizado.

_Nota_: Puede ocurrir que Python no tenga NumPy en tu instalacion, lo resuelves con pip install numpy o similar según tu sistema.

# Acceso y modificación de elementos de la matriz

Podemos acceder y modificar elementos de la matriz utilizando índices. Veamos algunos ejemplos:

In [2]:
# Acceder a un elemento
print("A[0, 0] =", A[0, 0])

# Modificar un elemento
A[0, 0] = 10
print("\nA =\n", A)

A[0, 0] = 1

A =
 [[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


# Operaciones básicas con matrices

NumPy nos permite realizar varias operaciones con matrices, como suma, resta, producto escalar, producto de matrices y división. Veamos cómo hacerlo:

In [3]:
# Crear dos matrices para las operaciones
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Suma de matrices
print("A + B =\n", A + B)

# Resta de matrices
print("\nA - B =\n", A - B)

# Producto escalar
print("\n2 * A =\n", 2 * A)

# Producto de matrices
print("\nA @ B =\n", A @ B)

# División de matrices
print("\nA / B =\n", A / B)

A + B =
 [[ 6  8]
 [10 12]]

A - B =
 [[-4 -4]
 [-4 -4]]

2 * A =
 [[2 4]
 [6 8]]

A @ B =
 [[19 22]
 [43 50]]

A / B =
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


# Algunas operaciones especiales con matrices

Además de las operaciones básicas, NumPy también nos permite realizar algunas operaciones especiales con matrices, como transposición, determinante, inversa, traza y rango. Veamos cómo hacerlo:

In [ ]:
# Transposición de una matriz
print("A.T =\n", A.T)

# Determinante de una matriz
print("\nnp.linalg.det(A) =", np.linalg.det(A))

# Inversa de una matriz
print("\nnp.linalg.inv(A) =\n", np.linalg.inv(A))

# Traza de una matriz
print("\nnp.trace(A) =", np.trace(A))

# Rango de una matriz
print("\nnp.linalg.matrix_rank(A) =", np.linalg.matrix_rank(A))

# Desafío 1

Considere las matrices $ A $ y $ B $ definidas como:

$ A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} $     y     $ B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix} $

Tu tarea es calcular la matriz resultante de la operación $ (2A + B^T) $. Recuerda que $ B^T $ denota la transposición de la matriz $ B $.

Paso 1: Importar la librería numpy

Antes de hacer cualquier cosa, necesitamos importar una librería en Python que nos ayuda a trabajar con matrices de manera más sencilla.

Paso 2: Definir las matrices A y B

np.array() toma una lista de listas (donde cada lista interna representa una fila de la matriz) y las convierte en una matriz o arreglo bidimensional de numpy.

Paso 3: Realización de la operación 2A+B^T

En esta línea se realizan varias operaciones se multiplica la matriz A por 2 y se suma a la transposición de la matriz .

Paso 4: Se muestra el resultado

array es parte de la representación textual del objeto en numpy, que te indica que el resultado es un numpy array y no una lista normal de Python o cualquier otra estructura de datos.

El término array aparece en el resultado para dejar claro que estás trabajando con un numpy array, lo que implica que puedes aprovechar todas las funcionalidades y operaciones que numpy ofrece para este tipo de estructura de datos.


In [1]:
# Paso 1: Importar la librería numpy
# NumPy es necesaria para trabajar con matrices y realizar cálculos de álgebra lineal.
import numpy as np

# Paso 2: Definir las matrices A y B
# np.array permite crear matrices a partir de listas. Cada lista interna representa una fila.
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Paso 3: Realizar la operación 2A + B^T
# Multiplicamos A por 2 y sumamos la transposición de B (B.T).
# A * 2 realiza una multiplicación escalar, y B.T calcula la transposición de B.
result = 2 * A + B.T

# Paso 4: Mostrar el resultado
# Imprimimos el resultado final de la operación.
print("Resultado de la operación 2A + B^T:\n", result)

Resultado de la operación 2A + B^T:
 [[ 7 11]
 [12 16]]


# Desafío 2

Dada la matriz $ A = \begin{bmatrix} 1 & 0 & 1 \\ 4 & -1 & 4 \\ 5 & 6 & 7 \end{bmatrix} $, encuentra la traza de la matriz inversa de $ A $.

[¿Qué es la traza de una matriz?](https://youtu.be/11pg99dfj10?si=vg7x8VCHdbIb5I3u)

La traza de una matriz cuadrada (matriz con igual número de filas y columnas) es la suma de los elementos en su diagonal principal.

​
[Inversa de una matriz de 3x3 método de Gauss Jordans](https://youtu.be/MRWPhA5RQyA?si=L6q1P-AtkLYqVJR-)
- Escribe tu matriz 3x3 original.
- Al lado, escribe una matriz identidad 3x3 (unos en la diagonal principal, ceros en el resto).
- Ahora, usa operaciones con filas para convertir tu matriz original en la identidad matriz. Cada operación que hace en las matriz original, hazla también en la matriz identidad.
- Cuando terminas, la matriz original se ha convertido en la identidad, y la era de la identidad se ha convertido en la inversa que buscabas.


Para resolver este problema, seguimos los siguientes pasos en el código:

- Definir la matriz A: Utilizamos numpy para crear la matriz. Esta línea crea una matriz A de 3x3 usando np.array(). Las filas de la matriz se pasan como listas dentro de una lista mayor.

- Calcular la matriz inversa de A: numpy tiene una función np.linalg.inv() que calcula la inversa de una matriz.

np.linalg.inv(A) calcula la inversa de la matriz AA. La función linalg (abreviatura de "lógica lineal") pertenece a la sublibrería de numpy dedicada a operaciones de álgebra lineal.

- Calcular la traza de la matriz inversa: Usamos np.trace() para sumar los elementos de la diagonal principal de la matriz inversa. np.trace() toma como entrada la matriz inversa calculada y suma los elementos de su diagonal principal. Este valor es la traza de la matriz inversa.

- Finalmente, el valor de la traza de la matriz inversa se guarda en la variable traza_inv_A y se muestra como salida.

In [2]:
import numpy as np  # Importamos la librería numpy para trabajar con matrices

# Definir la matriz A 
# Crear la matriz 3x3 especificada en el desafío.
A = np.array([[1, 0, 1],  # Primer fila de la matriz A
              [4, -1, 4], # Segunda fila de la matriz A
              [5, 6, 7]]) # Tercera fila de la matriz A

# Calcular la traza de la matriz inversa de A
traza_inv_A = np.trace(np.linalg.inv(A)) # np.linalg.inv calcula la inversa de una matriz si esta es invertible.

# Paso 5: Mostrar el resultado
# Mostramos el valor de la traza de la matriz inversa.
print("La traza de la matriz inversa de A es:", traza_inv_A)


La traza de la matriz inversa de A es: 15.00000000000002


# Desafío 3

Dada la matriz $ A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix} $, encuentra el rango de la matriz resultante de $ (A + A^T) $.

## ¿Qué es el rango de una matriz?

El rango de una matriz es el número máximo de columnas (o filas) linealmente independientes en la matriz. En otras palabras, el rango nos indica cuánta información contiene la matriz en términos de independencia lineal de sus filas o columnas. Un rango completo (igual al número de filas o columnas) significa que las filas/columnas no son lineales, mientras que un rango menor implica dependencia entre ellas.

Para resolver este desafío, primero vamos a calcular la matriz $ (A + A^T) $ y luego obtener su rango utilizando la función **np.linalg.matrix_rank()** de NumPy, que devuelve el rango de una matriz.

In [3]:
# Paso 1: Importar numpy para trabajar con matrices
import numpy as np

# Paso 2: Definir la matriz A
# Creamos la matriz 3x3 especificada en el desafío.
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Paso 3: Calcular A + A^T
# La transposición de la matriz A se obtiene con A.T, y luego sumamos A con A^T.
A_transpuesta = A.T
resultado = A + A_transpuesta

# Paso 4: Calcular el rango de la matriz resultante
# np.linalg.matrix_rank() nos da el rango de la matriz.
rango_resultante = np.linalg.matrix_rank(resultado)

# Paso 5: Mostrar el resultado
print("Matriz A + A^T:\n", resultado)
print("Rango de la matriz A + A^T:", rango_resultante)

Matriz A + A^T:
 [[ 2  6 10]
 [ 6 10 14]
 [10 14 18]]
Rango de la matriz A + A^T: 2


Explicación paso a paso del código:

Paso 1: Importamos **numpy** como **np**, que es la librería estándar para trabajar con matrices en Python.

Paso 2: Definimos la matriz A, que es la que se va a utilizar para calcular $ (A + A^T) $.

Paso 3: Calculamos $  A^T $ (la transposición de A) usando el atributo **.T** de **numpy**. Luego sumamos AA con su transposición.

Paso 4: Usamos la función **np.linalg.matrix_rank()** para calcular el rango de la matriz resultante. Esta función devuelve el número de columnas linealmente independientes de la matriz.

Paso 5: Imprimimos la matriz $ (A + A^T) $ y su rango para verificar el resultado.

# Desafío 4: Batalla Naval

Para este desafío, tendrás que implementar un juego sencillo de "Batalla Naval". El tablero de juego será una matriz de 5x5 donde el agua será representada por ceros (0) y los barcos por unos (1).

Primero, crea un tablero de juego utilizando NumPy, que será una matriz de ceros de 5x5.

Luego, coloca tres barcos en el tablero de juego. Cada barco es un 1 y debes colocarlo en una posición aleatoria en el tablero. No te preocupes por el tamaño de los barcos; cada barco ocupará solo una celda.

Finalmente, crea una función que acepte dos argumentos (las coordenadas x, y), y que verifique si en esa posición hay un barco (1) o agua (0). La función debe imprimir un mensaje indicando si se golpeó un barco o si el disparo cayó al agua.

Link a la Batalla Naval: https://replit.com/@milagrospozzofa/G2-Tarea-37b

# Desafío 5: Crear una simulación de "vida artificial" en un tablero de juego (matriz)
En este desafío, implementarás una simulación del famoso Juego de la vida de Conway. Se trata de un autómata celular desarrollado por el matemático británico John Horton Conway en 1970. Es un juego de cero jugadores, lo que significa que su evolución se determina por su estado inicial, sin necesidad de más entradas humanas.

### Objetivos del Desafío
Crear el Tablero de Juego:

Implementa una función para crear un tablero de juego de dimensiones n x m, donde cada celda puede estar viva (1) o muerta (0). Inicializa el tablero con un patrón inicial.

### Definir las Reglas del Juego:

Cada celda en el tablero tiene 8 vecinos. Las reglas para la evolución del estado de las celdas son:
Una celda viva con menos de dos celdas vecinas vivas muere por subpoblación.
Una celda viva con dos o tres celdas vecinas vivas sigue viva en la siguiente generación.
Una celda viva con más de tres celdas vecinas vivas muere por sobrepoblación.
Una celda muerta con exactamente tres celdas vecinas vivas se convierte en una celda viva por reproducción.

### Simular la Evolución:

Implementa una función para actualizar el tablero siguiendo las reglas del juego. Esta función debería generar la nueva configuración del tablero después de un número específico de iteraciones.

### Visualizar la Simulación:

Utiliza Matplotlib para visualizar la evolución del tablero a lo largo de las iteraciones. Muestra cada estado del tablero como una imagen en una animación.

➡️Implementar una simulación del Juego de la Vida de Conway, un autómata celular donde las celdas pueden estar vivas o muertas. La evolución del sistema se basa en un conjunto de reglas simples aplicadas a cada celda en una matriz, que representan si una célula sobrevive, muere o se reproduce en función del estado de sus celdas vecinas.

Aquí están los pasos principales y el código en Python para implementar esta simulación:
Reglas del Juego de la Vida de Conway:

    Subpoblación: Una celda viva con menos de 2 vecinos vivos muere.
    Supervivencia: Una celda viva con 2 o 3 vecinos vivos continúa viva.
    Sobrepoblación: Una celda viva con más de 3 vecinos vivos muere.
    Reproducción: Una celda muerta con exactamente 3 vecinos vivos se convierte en una celda viva.

In [ ]:
# Importamos las librerías necesarias
import numpy as np  # NumPy para manejar matrices y operaciones eficientes
import matplotlib.pyplot as plt  # Matplotlib para visualizar la simulación
import matplotlib.animation as animation  # Para animar la simulación

# Paso 1: Crear el tablero de juego con celdas vivas y muertas
def crear_tablero(filas, columnas):
    # Generamos un tablero de tamaño filas x columnas con valores aleatorios de 0 y 1
    # 0 representa una celda muerta y 1 representa una celda viva
    tablero = np.random.choice([0, 1], size=(filas, columnas))
    return tablero  # Retornamos el tablero generado

# Paso 2: Definir una función para contar vecinos vivos de una celda
def contar_vecinos(tablero, x, y):
    # Calculamos la cantidad de vecinos vivos alrededor de la celda en posición (x, y)
    # La matriz es toroidal, por lo que los bordes están conectados
    vecinos_vivos = (
        tablero[(x-1) % tablero.shape[0], (y-1) % tablero.shape[1]] +  # vecino superior-izquierda
        tablero[(x-1) % tablero.shape[0], y % tablero.shape[1]] +        # vecino superior
        tablero[(x-1) % tablero.shape[0], (y+1) % tablero.shape[1]] +    # vecino superior-derecha
        tablero[x % tablero.shape[0], (y-1) % tablero.shape[1]] +        # vecino izquierda
        tablero[x % tablero.shape[0], (y+1) % tablero.shape[1]] +        # vecino derecha
        tablero[(x+1) % tablero.shape[0], (y-1) % tablero.shape[1]] +    # vecino inferior-izquierda
        tablero[(x+1) % tablero.shape[0], y % tablero.shape[1]] +        # vecino inferior
        tablero[(x+1) % tablero.shape[0], (y+1) % tablero.shape[1]]      # vecino inferior-derecha
    )
    return vecinos_vivos  # Retornamos la cantidad de vecinos vivos

# Paso 3: Actualizar el tablero aplicando las reglas del Juego de la Vida
def actualizar_tablero(tablero):
    # Creamos una copia del tablero para almacenar el siguiente estado
    nuevo_tablero = np.copy(tablero)
    # Iteramos sobre cada celda del tablero
    for x in range(tablero.shape[0]):
        for y in range(tablero.shape[1]):
            # Contamos los vecinos vivos de la celda actual
            vecinos_vivos = contar_vecinos(tablero, x, y)
            # Reglas del juego:
            if tablero[x, y] == 1:  # Si la celda está viva
                # Muere por subpoblación o sobrepoblación
                if vecinos_vivos < 2 or vecinos_vivos > 3:
                    nuevo_tablero[x, y] = 0  # La celda muere
            else:  # Si la celda está muerta
                # Nace una nueva celda si tiene exactamente 3 vecinos vivos
                if vecinos_vivos == 3:
                    nuevo_tablero[x, y] = 1  # La celda cobra vida
    return nuevo_tablero  # Retornamos el nuevo estado del tablero

# Paso 4: Configurar la animación para visualizar el juego
def animar_juego(filas, columnas, iteraciones):
    # Inicializamos el tablero de juego con tamaño filas x columnas
    tablero = crear_tablero(filas, columnas)
    # Creamos una figura y ejes para la animación
    fig, ax = plt.subplots()
    
    # Función de actualización que se llama en cada frame de la animación
    def actualizar_cuadro(i):
        # Limpiamos los ejes para mostrar el nuevo estado del tablero
        ax.clear()
        # Mostramos el tablero actual como una imagen en escala de grises (0 y 1)
        ax.imshow(tablero, cmap='binary')  # `binary` muestra las celdas vivas en negro y muertas en blanco
        ax.set_title(f"Generación {i+1}")  # Título con la generación actual
        ax.axis('off')  # Desactivamos los ejes para una mejor visualización
        nonlocal tablero  # Declaramos que modificaremos la variable `tablero` de fuera del ámbito
        tablero = actualizar_tablero(tablero)  # Actualizamos el tablero para la siguiente generación
    
    # Creamos la animación llamando a `actualizar_cuadro` en cada frame
    animacion = animation.FuncAnimation(fig, actualizar_cuadro, frames=iteraciones, interval=200)
    plt.show()  # Mostramos la animación en pantalla

# Ejecutar la simulación con un tablero de 20x20 y 100 iteraciones
animar_juego(20, 20, 100)  # Tamaño del tablero: 20x20, iteraciones: 100

Explicación detallada:

    Librerías:
        numpy: Se usa para crear y manipular el tablero de celdas vivas y muertas.
        matplotlib.pyplot: Nos permite graficar y visualizar la simulación.
        matplotlib.animation: Nos permite animar la simulación mostrando la evolución del tablero en cada generación.

    Función crear_tablero:
        Esta función genera un tablero inicial de tamaño especificado por filas y columnas.
        Cada celda tiene un valor aleatorio de 0 (muerto) o 1 (vivo).

    Función contar_vecinos:
        Esta función calcula cuántos vecinos vivos (1) rodean una celda específica en el tablero.
        Utilizamos el operador % para que la matriz sea toroidal (los bordes están conectados, como si el tablero envolviera en ambos lados).

    Función actualizar_tablero:
        Itera sobre cada celda en el tablero, aplica las reglas del Juego de la Vida y genera un nuevo estado para el tablero.
        Si la celda está viva (1):
            Muere por subpoblación si tiene menos de 2 vecinos vivos.
            Muere por sobrepoblación si tiene más de 3 vecinos vivos.
            Sobrevive si tiene 2 o 3 vecinos vivos.
        Si la celda está muerta (0):
            Cobra vida si tiene exactamente 3 vecinos vivos (por reproducción).

    Función animar_juego:
        Configura la animación de la simulación y muestra el tablero evolucionando con cada generación.
        actualizar_cuadro: Función que se llama en cada frame de la animación:
            Limpia el tablero anterior y muestra el nuevo estado del tablero.
            Actualiza el tablero aplicando las reglas para la siguiente generación.
        FuncAnimation: Crea la animación llamando a actualizar_cuadro en cada iteración para mostrar la simulación.

    Llamada final a animar_juego(20, 20, 100):
        Inicia la simulación en un tablero de 20x20 celdas con un total de 100 generaciones para observar la evolución de la simulación.

Este código crea una animación de la evolución de "vida" en un tablero de celdas aplicando las reglas de Conway en cada generación. Cada celda puede "nacer", "morir" o "sobrevivir" según el número de vecinos vivos.